services:
  web:
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK:-traefik_proxy}
      - traefik.http.routers.inyice-os.rule=Host(`${APP_DOMAIN:-os.inyice.com}`)
      - traefik.http.routers.inyice-os.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
      - traefik.http.routers.inyice-os.tls=true
      - traefik.http.routers.inyice-os.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}
      - traefik.http.services.inyice-os.loadbalancer.server.port=80
    networks:
      - app_net
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik_proxy}
