version: "3.9"

services:
  web:
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK:-traefik_proxy}
      - traefik.http.routers.inyice.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.inyice.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}
      - traefik.http.routers.inyice.tls=true
      - traefik.http.routers.inyice.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencrypt}
      - traefik.http.services.inyice.loadbalancer.server.port=80
    networks:
      - app_net
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik_proxy}
